name: eramyadak_shop
description: Eram Yadak WooCommerce Flutter app (RTL, Yellow Theme)
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.10.5
  webview_flutter_wkwebview: ^3.23.1
  http: ^1.2.2
  intl: ^0.20.2
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/baner/   # ✅ کل پوشهٔ پوسترها (اسم دقیق پوشه‌ات همینه: baner)

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android: true
  ios: true
  web: false
  android_12:
    icon_background_color: "#FFFFFF"
    image: assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
